import pygame


SCREEN_WIDTH = 640*2
SCREEN_HEIGHT = 720
SCREEN_RES = (SCREEN_WIDTH,SCREEN_HEIGHT)

BOID_HEIGHT = 30
BOID_WIDTH = 15
HOIK_HEIGHT = 30
HOIK_WIDTH = 15

RED = (255,0,0)
HOIK_COLOR = RED
WHITE = (255,255,255)
GREEN = (0,0,255)

BOID_IMAGE_FNAME = "images/boid_t.png"
BOID_IMAGE = pygame.image.load(BOID_IMAGE_FNAME)
HOIK_IMAGE_FNAME = "images/hoik_t.png"
HOIK_IMAGE = pygame.image.load(HOIK_IMAGE_FNAME)
OBSTACLE_IMAGE_FNAME = "images/obstacle_t.png"
OBSTACLE_IMAGE = pygame.image.load(OBSTACLE_IMAGE_FNAME)

START_VELOCITY_X = 10
START_VELOCITY_Y = -10

OBSTACLE_1_X = 150 
OBSTACLE_1_Y = 150
OBSTACLE_1_SIZE = 100
OBSTACLE_2_X = 350
OBSTACLE_2_Y = 300
OBSTACLE_2_SIZE = 120

SIGHT_RADIUS = 60
COHESION_POWER = 1/100
ALIGNMENT_POWER = 1/8
TOWARDS_PREY_POWER = 1/2
SEPARATION_POWER = 1/20
AVOID_OBSTACLE_POWER = 2

BOID_MAX_SPEED = 10
HOIK_MAX_SPEED = 10
MAX_ACCELERATION = 10

HIT_RADIUS = 5

BORDER_SCREEN_RATIO = 0.15
TURN_BACK_SPEED = 0.5
WALL_POWER = 0.7
